### ISSUE TITLE
Not displayed terms on GUI

### ISSUE THREAD

**Issue by onon765trb** [DigitalMediaServer/DigitalMediaServer#96] opened 2018-10-03 09:04 UTC
The below happens even in English env..

Some terms are not displayed on Transcoding tab.
Scroll bars are not displayed on Transcoding tab.
Explanation and buttons are not displayed on restart confirm dialogue of language of general tab.
Explanation and buttons are not displayed when selecting "Ask" on Close action of general tab and closing the window of DMS.
Explanation and buttons are not displayed on the dialogue of Question, Configuration wizard Question 1 of 2, Configuration wizard Question 2 of 2, Wizard complete! on the wizard.

I do not touch these because I do not know causes.
Only mac?

I fixed "Some terms are not displayed on Transcoding tab".

**Comment by Nadahar** [comment] 2018-10-03 09:28
I'm not sure I understand completely what you mean. Could you make a screenshot of one of these and attach it here? You can simply drag and drop an image into your comment.

**Comment by onon765trb** [comment] 2018-10-03 09:54
Screen shots
![scc1](https://user-images.githubusercontent.com/24803846/46403487-9ade6a00-c73d-11e8-8310-26f23f0e2e15.png)
![scc2](https://user-images.githubusercontent.com/24803846/46403488-9ade6a00-c73d-11e8-9d4d-102ab2b94cba.png)
![scc3](https://user-images.githubusercontent.com/24803846/46403489-9ade6a00-c73d-11e8-887b-fca90087cd49.png)
![scc4](https://user-images.githubusercontent.com/24803846/46403491-9b770080-c73d-11e8-9b2a-60937441bf4e.png)
![scc5](https://user-images.githubusercontent.com/24803846/46403493-9b770080-c73d-11e8-8e0b-618092f14e82.png)
![scc6](https://user-images.githubusercontent.com/24803846/46403494-9b770080-c73d-11e8-936b-8b11e868c4d6.png)
![scc7](https://user-images.githubusercontent.com/24803846/46403496-9b770080-c73d-11e8-97eb-ffe21d24e5e9.png)
![scc8](https://user-images.githubusercontent.com/24803846/46403497-9c0f9700-c73d-11e8-821b-dc745096ad46.png)

**Comment by Nadahar** [comment] 2018-10-03 13:30
Thank you for the screenshots. As I tried to explain earlier, the first two screenshots have already been fixed in #34. I haven't fixed it in `master` to avoid merge conflicts.

When it comes to the other screenshots, I can't reproduce it:

![japanesewizard](https://user-images.githubusercontent.com/12900583/46412371-aa01ef80-c71e-11e8-8aed-9ce19c7f8ade.png)

I'm wondering if they are caused by how you're building DMS. There are many ways to do it, but the way I find simplest is to do the following from a terminal:
* `cd` to the root of the DMS repo (where you have cloned it), so that you are in the `DigitalMediaServer` folder.
* Make sure that you're local Git repo is up to date: `git fetch`.
* Check that you're on the correct branch, and that it's up to date: `git status`.
  * If `git status` says that you're on the wrong branch, check out the branch you want: `git checkout master` (if `master` is the branch you want). Run `git status` again.
  * If `git status` says the your branch is behind but can be fast-forwarded, run `git pull`.
  * If `git status` says that the local and remote branch has diverged it gets more complicated. If you want to keep your local changes, you could create a new branch first, which will keep your local changes. If you're OK with losing your local changes, or you have already created a new branch with them, make sure you're still checked out to the correct branch (for example `master`) and run: `git reset --hard origin/master`.
* Once `git status` confirms that you're on the correct branch and that it's up to date with the remote branch, start building DMS by running: `mvn package -Posx-java8`.
* Once the build is finished, start DMS with: `java -jar target/dms.jar`.

There are many other ways to do these things, the important thing is to make sure that your local branch is "in sync" with the remote branch you want to build before you start building. If you use Eclipse, you can skip the last two steps, and simply press `⌘ + F11` instead. It might be smart to press `F5` while the DMS project is selected in Eclipse after changing branches or doing other Git stuff, to make sure that Eclipse is aware of any changes to the source files.

**Comment by Nadahar** [comment] 2018-10-03 20:44
@onon765trb I realized after writing the above that the "remote name" for this repo probably isn't `origin` in your case, since that is probably the name of [your fork](https://github.com/onon765trb/DigitalMediaServer). I don't know what remote name you are using for this repo, but you probably know :wink: Replace `origin` in the above text with the actual remote name you use for this repo.

In case you're not sure of what your remote repos are called, run: `git remote -v`. This will list every remote twice (one for read and one for write). The remote pointing to https://github.com/DigitalMediaServer/DigitalMediaServer.git is the one you want to reference.

If you don't have a remote for this repo, you should add it. To add it with the name `upstream`, simply run: `git remote add upstream https://github.com/DigitalMediaServer/DigitalMediaServer.git`.

Once that's done, I'd recommend that you set your local master branch to track master in this repo, not in your fork. To do that, run:
`git checkout master`
`git branch -u <remote name>/master`
If the remote name is `upstream`, the command will thus be:
`git branch -u upstream/master`

When this is done, you can always compare your local `master` branch with the "official" one simply by running (when having `master` checked out):
`git fetch`
`git status`

**Comment by Nadahar** [comment] 2018-10-03 20:47
If this isn't caused by a build problem, I think it must be caused by some kind of font problem. I don't know much about Japanese character sets and fonts, but if you're not using a Unicode font it could explain the behavior.

**Comment by onon765trb** [comment] 2018-10-04 11:43
I tried to build More TODOs acadff31b1534d592cc915b13d373e7743bf6617 of PR #34.
But, I cannot. a log
```
ERROR] Failures: 
[ERROR]   FileUtilTest.testGetFileNameWithRewriting:125 expected:<"Digital[ Media Server (2018)]"> but was:<"Digital[_Media_Server_(2018)_[720p,BluRay,flac,x264]_-_FANSUBBERS]">
[INFO] 
[ERROR] Tests run: 404, Failures: 1, Errors: 0, Skipped: 6
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.924 s
[INFO] Finished at: 2018-10-04T08:59:14+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project dms: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/x/DigitalMediaServer/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
dumpstream
`Java HotSpot(TM) 64-Bit Server VM warning: ignoring option UseSplitVerifier; support was removed in 8.0`

**Comment by onon765trb** [comment] 2018-10-04 11:51
mistaking

**Comment by Nadahar** [comment] 2018-10-04 11:53
@onon765trb I know why it fails, I'm still working on this branch so one of the tests currently fail. Add `-DskipTests` to your `mvn` build command and it should work just fine.

**Comment by Nadahar** [comment] 2018-10-04 11:55
Be aware that some of the other macOS fixes that exist in master doesn't yet exist in this branch ;)

**Comment by Nadahar** [comment] 2018-10-06 11:37
@onon765trb I don't understand what's causing this. It seems like some kind of screen update/draw problem.

Is it correct that you only have this problem with "external" windows that's not the main GUI window? Do you have the same problem with for example the startup wizard in UMS?

It's also strange that I can't replicate it on my macOS VM. I'm running 10.12 with Java 8. What version of macOS and Java are you running?

**Comment by Sami32** [comment] 2018-10-06 15:09
@onon735trb It shouldn't be related to that issue but i'm curious to know if you are using a Retina screen?

**Comment by onon765trb** [comment] 2018-10-07 07:08
@Nadahar
>Is it correct that you only have this problem with "external" windows, not the "main" GUI window? 

I never have seen it on "main" GUI window.

>Do you have the same problem with for example the configuration wizard in UMS?

I don't have the same problem with the configuration wizard in UMS.
In DMS, all buttons are displayed on configuration wizard: question 1 of 2 and 2 of 2 and complete.

>What version of macOS and Java are you running?

 I'm running 10.12 with Java 8.

@Sami32 
Yes, Retina. Beautiful and clear!
But the noise of video, too......

**Comment by Nadahar** [comment] 2018-10-08 16:50
@onon765trb I've finally been able to reproduce it. The problem doesn't occur if you run DMS using `java -jar target/dms.jar` or using Eclipse.

However, if you build the full appbundle and then run the "Application" that is created, I get the same issue, with any language.

I've tracked the issue to 5088f3cb4364709fea680ffd090a8872dcd11a0d. That means that if you check out 03a22aa3ab00220b6687a2ace927623252f5d067 you should not experience this issue. Can you confirm that?

**Comment by Nadahar** [comment] 2018-10-08 17:07
It seems like what's causing the problem is the change to [`/src/main/resources/images/logo.icns`](https://github.com/DigitalMediaServer/DigitalMediaServer/blob/5088f3cb4364709fea680ffd090a8872dcd11a0d/src/main/resources/images/logo.icns).

The new file I generated must somehow be invalid I guess. It's very unexpected that changing the application logo can cause such issues though.

**Comment by Nadahar** [comment] 2018-10-09 13:45
@onon765trb Forget about testing the above commit, if you could build and test #100 instead that would be great. #100 fixes the issue on my macOS VM.

**Comment by onon765trb** [comment] 2018-10-10 00:54
I will try. Please wait.

**Comment by onon765trb** [comment] 2018-10-10 10:04
I cannot find problems. All buttons and explanation are displayed.

**Comment by onon765trb** [comment] 2018-10-10 10:09
There is what I mind after looking the wizard.
To avoid the confusion of issues, I will open a issue.

You can close this ISSUE, PR #100 is completed.

**Comment by Nadahar** [comment] 2018-10-10 10:28
Great and thank you for testing :+1:

**Closed** 2018-10-10 14:07 UTC
